# Generated by Django 5.1.15 on 2026-07-20 03:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("en-route", "En route"),
                            ("pickup", "Pickup"),
                            ("dropoff", "Dropoff"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("pickup_latitude", models.FloatField()),
                ("pickup_longitude", models.FloatField()),
                ("dropoff_latitude", models.FloatField()),
                ("dropoff_longitude", models.FloatField()),
                ("pickup_time", models.DateTimeField(db_index=True)),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rides_as_driver",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rides_as_rider",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-pickup_time"],
            },
        ),
        migrations.CreateModel(
            name="RideEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ride",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="rides.ride",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="ride",
            index=models.Index(
                fields=["pickup_latitude", "pickup_longitude"],
                name="rides_ride_pickup__b78bad_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="rideevent",
            index=models.Index(
                fields=["ride", "created_at"], name="rides_ridee_ride_id_277de8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rideevent",
            index=models.Index(
                fields=["description", "ride", "created_at"],
                name="rides_ridee_descrip_dd03fe_idx",
            ),
        ),
    ]
